version: '3'
services:


        # Database for the project
        mongo:
                # Build the database 
                build: ./db

                # Set the host port and container port to default mongodb port (27017)
                ports:
                        - "27017:27017"

                # Try to restart container if it crashes or stops
                restart: always


        # Build the server from build folder
        server:
        
                # Build the server with the dockerfile in the designated folder
                build: ./server
        
                # Set the host port to 8080 and the container port to 8080
                ports: 
                        - 3000:3000

                # Wait for the database to spin up
                depends_on:
                        - mongo
                        
                # Try to restart container if it crashes or stops
                restart: always                


        # Primary application for project
        mongo-express:
                # Use the default mongo-express image for mongoDB management
                image: mongo-express

                # Use port 8080 for both host and container
                ports:
                        - "8081:8081"

                # Set the startup root username and password
                environment:
                        ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
                        ME_CONFIG_MONGODB_ADMINPASSWORD: "password"

                # Wait for the database to spin up
                depends_on:
                        - mongo

                # Try to restart container if it crashes or stops
                restart: always

